### ISSUE TITLE
Reformat Codebase w/ WebSharks PhpStorm Style

### ISSUE THREAD

**Issue by jaswrks** [websharks/s2-domains#1]
Reformat Codebase w/ WebSharks PhpStorm Style

**Comment by jaswrks** [comment]
@brucewsinc Just checking. Did you already do this when you worked on the code for this before?

**Comment by brucewrks** [comment]
Yes, but it may need to be reformatted since there were changes to the PhpStorm styles since then

**Comment by jaswrks** [comment]
Cool. Would you mind running over that for me and knock this issue out?

**Comment by brucewrks** [comment]
@jaswsinc It looks like I don't have push access for the repo anymore. Could you take a look at that for me?

**Comment by raamdev** [comment]
> It looks like I don't have push access for the repo anymore. Could you take a look at that for me?

This should be fixed. I created a new `s2-domains-team` for this repo and gave @brucewsinc admin access.

**Comment by brucewrks** [comment]
Thanks!
